version: '3.9'

services:
  postgres_db:
    expose:
      - '5432'
  node_nest_app:
    profiles: ['production']
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: ${NODE_STDIN_OPEN:-false}
    mem_limit: 1g
    cpus: 1.0
    tty: ${NODE_TTY:-false}
    expose:
      - '3000'

  nginx_service:
    volumes:
      - ./docker/nginx/nginx.production.conf:/etc/nginx/conf.d/default.conf
      - certs-production:/etc/letsencrypt
      - webroot:/var/www/letsencrypt
    ports:
      - '80:80'
      - '443:443'
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certs-production:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/letsencrypt --email ${LETSENCRYPT_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN} && crond -f"

    depends_on:
      - nginx_service

    networks:
      - frontend_network
